# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy production environment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy build on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        username: ${{ secrets.PRODUCTION_SERVER_USER }}
        password: ${{ secrets.PRODUCTION_SERVER_PASS }}
        port: 22
        script: |
          export COMMIT_SHA=$( echo '${{ toJSON(github) }}' | jq -r '.event.commits[-2].id' )
          cd ${{ secrets.PRODUCTION_SERVER_PROJECT_DIR }}
          rm -rf ./source && mkdir -p ./source
          sudo unzip ./builds/$COMMIT_SHA.zip -d ./source
          source ./venv/bin/activate
          pip3 install -r ./source/requirements.txt
          systemctl restart ${{ secrets.PRODUCTION_SERVER_SERVICE_NAME }}.service